# Generated by Django 5.0.7 on 2024-10-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
    ]
