# Generated by Django 5.0.7 on 2024-10-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'Akıncı'), ('KIZILELMA', 'Kızılelma')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KANAT', 'Kanat Takımı'), ('GOVDE', 'Gövde Takımı'), ('KUYRUK', 'Kuyruk Takımı'), ('AVIYONIK', 'Aviyonik Takımı'), ('MONTAJ', 'Montaj Takımı')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_type', models.CharField(choices=[('KANAT', 'Kanat'), ('GOVDE', 'Gövde'), ('KUYRUK', 'Kuyruk'), ('AVIYONIK', 'Aviyonik')], max_length=20)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plane_parts', to='uretim.plane')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlanePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(default=1)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.part')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.plane')),
            ],
            options={
                'unique_together': {('plane', 'part')},
            },
        ),
        migrations.AddField(
            model_name='plane',
            name='parts',
            field=models.ManyToManyField(related_name='planes', through='uretim.PlanePart', to='uretim.part'),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.team')),
            ],
        ),
    ]
