# Generated by Django 5.0.7 on 2024-10-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
