# Generated by Django 5.0.7 on 2024-10-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0002_delete_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('KANAT', 'KANAT'), ('GOVDE', 'GOVDE'), ('KUYRUK', 'KUYRUK'), ('AVIYONIK', 'AVIYONIK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='plane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uretim.plane'),
        ),
    ]
