# Generated by Django 5.0.7 on 2024-10-15 18:50

from django.db import migrations


def create_teams_and_planes(apps, schema_editor):
    Team = apps.get_model('uretim', 'Team')
    Plane = apps.get_model('uretim', 'Plane')

    # Takım verilerini ekliyoruz (sadece büyük harflerle)
    teams = [
        ('KANAT',),
        ('GOVDE',),
        ('KUYRUK',),
        ('AVIYONIK',),
        ('MONTAJ',),
    ]

    for team_name in teams:
        Team.objects.create(name=team_name[0])

    # Uçak verilerini ekliyoruz
    planes = [
        ('TB2',),
        ('TB3',),
        ('AKINCI',),
        ('KIZILELMA',),
    ]

    for plane_model in planes:
        Plane.objects.create(name=plane_model[0])


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0003_remove_part_is_used_alter_part_part_type_and_more'),
    ]

    operations = [
        migrations.RunPython(create_teams_and_planes),
    ]
