# Generated by Django 5.0.7 on 2024-10-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uretim', '0002_delete_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assembled', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('TAMAMLANDI', 'Tamamlandı'), ('EKSİK', 'Eksik')], default='EKSİK', max_length=20)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.plane')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(default=1)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montaj.assembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uretim.part')),
            ],
        ),
    ]
